version: 2
updates:
  - package-ecosystem: npm
    directory: /Backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
  - package-ecosystem: npm
    directory: /Landing
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
