// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "AIKeyboardCore",
    platforms: [.iOS(.v17)],
    products: [
        .library(name: "AIKeyboardCore", targets: ["AIKeyboardCore"]),
        // Linked on its own by the broadcast upload extension, which must never
        // link `AIKeyboardCore`: that target imports SwiftUI and UIKit from a
        // dozen files, and dragging both into a process capped at ~50 MB buys
        // nothing. `AIKeyboardShared` is Foundation, CryptoKit, CoreGraphics and ImageIO only — no UIKit, no SwiftUI.
        .library(name: "AIKeyboardShared", targets: ["AIKeyboardShared"])
    ],
    targets: [
        // Seqlock fences. See Sources/CaptureAtomics/include/CaptureAtomics.h for
        // why they cannot be written in Swift on this toolchain.
        .target(name: "CaptureAtomics"),
        .target(name: "AIKeyboardShared", dependencies: ["CaptureAtomics"]),
        // `Resources/EmojiCatalog.json` is 1,870 emoji with their English and
        // Hebrew search words, generated by `Scripts/generate-emoji-catalog.py`.
        // A resource rather than a generated Swift file because 233 KB of string
        // literals is a compile cost paid on every build, and `EmojiCatalog` reads
        // it lazily on the first emoji tap rather than at launch.
        .target(
            name: "AIKeyboardCore", dependencies: ["AIKeyboardShared"],
            resources: [.process("Resources")])
    ]
)
