#!/usr/bin/env python3
"""Expands words.json into a corpus of one entry per keystroke.

    Bar/typing/sweep/expand.py                    # writes to stdout
    Bar/typing/sweep/expand.py /tmp/sweep.json    # writes a file
    SWEEP_WORDS=other.json Bar/typing/sweep/expand.py

The output is `Bar/typing/corpus.json`'s own shape, so `harness/run.sh` runs it
with nothing changed and `harness/main.swift` decodes it as it stands. Typing
`מכונית` becomes six entries with prefixes `מ`, `מכ`, `מכו`, `מכונ`, `מכוני`,
`מכונית`, all carrying the same context.

**The last keystroke is an entry too, and it is the one that matters most.** A
sweep that stopped one letter short would never ask what the space bar does to a
word the user has finished typing, which is the moment the keyboard has the most
evidence and the least excuse.

Two fields the frozen corpus does not have ride along, and Swift's decoder
ignores them: `word` (the whole word this moment is on the way to) and `intended`
(the same thing unless the entry says otherwise). `judge.py` needs them, and
carrying them in the expanded corpus keeps the judge from having to re-derive the
target by parsing ids.
"""

import json
import os
import pathlib
import sys
from datetime import datetime, timezone

HERE = pathlib.Path(__file__).resolve().parent


def words_path():
    if override := os.environ.get("SWEEP_WORDS"):
        return pathlib.Path(override)
    return HERE / "words.json"


def expand(words):
    entries = []
    counts = {}
    for item in words:
        word = item["word"]
        keyboard = item.get("keyboard", "en_US")
        language = "he" if keyboard.startswith("he") else "en"
        # Numbered per language rather than per file position, so adding an
        # English word at the end does not renumber every Hebrew id above it and
        # turn a re-run into an unreadable diff.
        counts[language] = counts.get(language, 0) + 1
        stem = f"{language}-{counts[language]:02d}"
        letters = list(word)
        for length in range(1, len(letters) + 1):
            entries.append({
                "id": f"{stem}-{length:02d}",
                "category": f"sweep-{language}",
                "language": language,
                "keyboard": keyboard,
                "context": item.get("context", ""),
                "prefix": "".join(letters[:length]),
                "word": word,
                "intended": item.get("intended", word),
                "probes": item.get("probes", f"letter-by-letter sweep of {word}"),
            })
    return entries


def main():
    source = json.loads(words_path().read_text())
    entries = expand(source["words"])
    corpus = {
        "schema": 1,
        "name": "Letter-by-letter sweep (generated)",
        "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "source": str(words_path()),
        "notes": (
            "Generated by Bar/typing/sweep/expand.py. Not a frozen corpus and not "
            "a regression guard: edit words.json and regenerate. The frozen exam is "
            "Bar/typing/corpus.json."
        ),
        "entries": entries,
    }
    text = json.dumps(corpus, ensure_ascii=False, indent=2) + "\n"
    if len(sys.argv) > 1:
        pathlib.Path(sys.argv[1]).write_text(text)
        print(
            f"{len(entries)} keystroke moments from {len(source['words'])} words"
            f" -> {sys.argv[1]}",
            file=sys.stderr,
        )
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
