#!/usr/bin/env python3
"""Builds Bar/grouped/data/lexicon-en.json and Bar/grouped/data/lexicon-he.json.

    Bar/grouped/.venv/bin/python Bar/grouped/make-lexicon.py

**What this data is.** The top N words of English and Hebrew by corpus
frequency, straight out of the `wordfreq` package's `best` wordlist, each with
its `word_frequency` value — a probability, not a Zipf score, so the numbers
sum to roughly 1 over the whole list and can be multiplied together directly by
a decoder. Order is descending frequency, which is the only thing the grouped-key
simulation needs: when several words share one key sequence, the frequent one
wins.

**What this data is NOT.** It is not a dictionary and not a spell-checker's
word list. wordfreq counts *tokens seen in text*, so the tail contains
misspellings, foreign words, emoji, digits, URLs fragments and profanity, and
nothing here has been curated or filtered. It is also not a model of what this
keyboard's users type — it is Wikipedia, subtitles, news, books, web text and
(for some languages) Twitter, in aggregate, from a snapshot the wordfreq
maintainer froze in 2021. Hebrew in particular has no clitic handling: `לעבודה`
and `עבודה` are two unrelated rows here, where
`Packages/.../LanguageModel.json` deliberately stores the bare stem and lets
`HebrewMorphology` do the joining.

**It is measurement-only.** wordfreq's *code* is Apache 2.0, but the *data* is
built from corpora with mixed and partly unstated licences (see the licence note
in `wordfreq`'s README). Nothing generated by this script may be bundled into a
shipping binary without a separate, deliberate licence review. It exists to
score a decoder in `Bar/grouped/`, nothing else.

Deterministic: wordfreq ships its counts as a frozen data file, so the same
version in gives the same JSON out. Safe to re-run.
"""

import json
import re
import sys
from datetime import date
from importlib.metadata import version
from pathlib import Path

try:
    from wordfreq import top_n_list, word_frequency
except ImportError:
    sys.exit(
        "wordfreq is not importable. This script runs from its own venv:\n"
        "    uv venv --python 3.13 Bar/grouped/.venv\n"
        "    VIRTUAL_ENV=Bar/grouped/.venv uv pip install wordfreq\n"
        "    Bar/grouped/.venv/bin/python Bar/grouped/make-lexicon.py"
    )

HERE = Path(__file__).resolve().parent
DATA_DIR = HERE / "data"

# Ask for more than we expect to need. wordfreq answers with whatever it has and
# never pads, so the count written into the file is the real one.
REQUESTED = 200_000
WORDLIST = "best"

# The Hebrew block, U+0590-U+05FF: letters, points and punctuation. Deliberately
# wider than the 22 letters so that a word carrying niqqud or a geresh is not
# reported as script-free.
HEBREW = re.compile(r"[֐-׿]")
ASCII_LETTER = re.compile(r"[A-Za-z]")
# ם ן ך ף ץ — the five letters that change shape at the end of a Hebrew word.
FINAL_FORMS = "םןךףץ"
NON_FINAL_OF = {"ם": "מ", "ן": "נ", "ך": "כ", "ף": "פ", "ץ": "צ"}

# Words a Hebrew keyboard user types constantly. If one of these is missing from
# a 200k list, the list is not what it claims to be — report it loudly rather
# than shipping a lexicon with no word for "thank you" in it.
HEBREW_SENTINELS = ["שלום", "תודה", "אני", "בסדר", "מה", "לא", "כן"]
ENGLISH_SENTINELS = ["the", "you", "thanks", "okay", "tomorrow", "meeting"]

LANGUAGES = [
    ("en", ASCII_LETTER, ENGLISH_SENTINELS),
    ("he", HEBREW, HEBREW_SENTINELS),
]


def build(lang):
    """Frequency-ranked (word, frequency) pairs, descending."""
    words = top_n_list(lang, REQUESTED, wordlist=WORDLIST)
    return [[w, word_frequency(w, lang, wordlist=WORDLIST)] for w in words]


def dump(payload):
    """Ordinary JSON, but one [word, frequency] pair per line.

    `indent=2` puts every pair on four lines, which is 9 MB and 800k lines for a
    200k list — grep-hostile and slow to parse. This is byte-for-byte the same
    document to any JSON reader, at a third of the size.
    """
    head = {k: v for k, v in payload.items() if k != "words"}
    lines = [json.dumps(head, ensure_ascii=False, indent=2)[:-2].rstrip() + ",",
             '  "words": [']
    rows = [f"    {json.dumps(p, ensure_ascii=False)}" for p in payload["words"]]
    lines.append(",\n".join(rows))
    lines.append("  ]\n}")
    return "\n".join(lines) + "\n"


def report(lang, script, sentinels, pairs):
    """Everything a reader needs to decide whether to trust this file.

    Nothing here filters. A lexicon that quietly dropped its odd entries would
    hide exactly the thing worth knowing about it.
    """
    words = [w for w, _ in pairs]
    rank = {w: i for i, w in enumerate(words)}
    freq = dict(pairs)

    print(f"\n{'=' * 70}\n{lang}: {len(pairs)} words (requested {REQUESTED})\n{'=' * 70}")

    print("\ntop 20:")
    for i, (w, f) in enumerate(pairs[:20]):
        print(f"  {i + 1:2}. {w!r:16} {f:.6g}")

    off_script = [w for w in words if not script.search(w)]
    print(f"\nentries with no {'Hebrew' if lang == 'he' else 'ASCII-letter'} character: "
          f"{len(off_script)} ({100 * len(off_script) / len(words):.2f}%)")
    print(f"  examples: {off_script[:10]}")

    if lang == "he":
        # Every non-final form that a *finished* word may not end in, and the
        # final forms in the position they belong in. Both counts matter: the
        # first is the orthography error the keyboard's own final-form rule
        # exists to fix, so a corpus full of it would be a bad teacher.
        ends_final = sum(1 for w in words if w and w[-1] in FINAL_FORMS)
        final_inside = sum(1 for w in words if any(c in FINAL_FORMS for c in w[:-1]))
        ends_nonfinal = sum(1 for w in words if w and w[-1] in NON_FINAL_OF.values())
        print(f"\nwords ending in a final form (ם ן ך ף ץ): {ends_final}")
        print(f"words with a final form NOT at the end:    {final_inside}")
        print(f"words ending in a non-final מ נ כ פ צ:      {ends_nonfinal}")
        for f in FINAL_FORMS:
            example = next((w for w in words if w.endswith(f)), None)
            print(f"  ...{f}: {example!r} (rank {rank[example] + 1})" if example
                  else f"  ...{f}: NONE FOUND")

    print("\nsentinels:")
    for s in sentinels:
        if s in rank:
            print(f"  {s!r:10} rank {rank[s] + 1:>7}  freq {freq[s]:.6g}")
        else:
            print(f"  {s!r:10} *** MISSING — red flag ***")


def main():
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    wf_version = version("wordfreq")

    for lang, script, sentinels in LANGUAGES:
        pairs = build(lang)
        report(lang, script, sentinels, pairs)

        payload = {
            "language": lang,
            "source": f"wordfreq {wf_version} top_n_list({lang!r}, {REQUESTED}, "
                      f"wordlist={WORDLIST!r})",
            "generated": date.today().isoformat(),
            "count": len(pairs),
            "words": pairs,
        }
        out = DATA_DIR / f"lexicon-{lang}.json"
        out.write_text(dump(payload), encoding="utf-8")
        print(f"\n-> {out} ({out.stat().st_size / 1e6:.1f} MB)")


if __name__ == "__main__":
    main()
