export type Locale = "en" | "he";

export const copy = {
  en: {
    skip: "Skip to content",
    wordmark: "AIKeyboard",
    localeName: "עברית",
    localeSwitch: "Switch to Hebrew",
    navCta: "Get the keyboard",
    heroTitleA: "A keyboard that",
    heroTitleEm: "writes",
    heroTitleB: "with you.",
    heroSub:
      "Reply, rewrite, and dictate in the app you are already in.",
    heroPrimary: "Get the keyboard",
    heroSecondary: "Watch it write",
    sceneFrom: "Maya",
    sceneIn: "Want to grab dinner Thursday night?",
    sceneOut: "Thursday at 7 works perfectly. See you then!",
    suggestions: ["Thursday works", "Sounds good", "See you then"],
    space: "English",
    actions: ["Reply", "Fix", "Rewrite"],
    dictate: "Dictate",
    storyTitle: "Watch one message come together.",
    storySub: "Scroll through one reply, written on the keys.",
    storyUnderstand: "Understand",
    storyUnderstandBody:
      "Reply reads the conversation and sees Maya asking about Thursday.",
    storyDraft: "Draft",
    storyDraftBody:
      "A fitting reply is written for you, right inside the message field.",
    storyRefine: "Refine",
    storyRefineBody:
      "Rewrite moves the tone from casual to professional in one tap.",
    storyDictate: "Dictate",
    storyDictateBody:
      "Speak one more sentence. It lands in the message, typed and punctuated.",
    storySend: "Send",
    storySendBody:
      "The finished message lifts into the chat. You never left the keyboard.",
    storyChip: "Maya asked about dinner on Thursday",
    storyRough: "Thanks! Thursday at 7 works.",
    storyRefined:
      "Thank you for the invite. Thursday at 7:00 works perfectly for me.",
    storySpoken: "See you then!",
    storyOut:
      "Thank you for the invite. Thursday at 7:00 works perfectly for me. See you then!",
    storySent: "Sent",
    featuresTitle: "The work happens on the keys.",
    featuresSub:
      "Three actions sit under your thumbs. The rest keeps typing clean.",
    screenTitle: "Reply",
    screenBody:
      "When you ask, it reads the conversation on screen and drafts a reply that fits, instead of starting from zero.",
    screenChip: "Read the invitation",
    rewriteTitle: "Rewrite",
    rewriteBody: "Reword a sentence, or shift its tone, in one tap.",
    casual: "Casual",
    professional: "Professional",
    dictateTitle: "Dictate",
    dictateBody: "Speak. It types, punctuates, and hears when you are done.",
    listening: "Listening",
    grammarTitle: "Grammar in place",
    grammarBody: "Spelling and grammar fixed in the language you are writing.",
    dictionaryTitle: "Personal dictionary",
    dictionaryBody: "Names and terms you teach it once, suggested from then on.",
    layoutsTitle: "Custom layouts",
    layoutsBody: "Arrange the keys the way your hands expect them.",
    languagesTitle: "Write in the language you are thinking in.",
    languagesSub:
      "Suggestions, corrections, and AI actions follow you across languages, in either direction.",
    languagesNote:
      "Your layout and your dictionary come with you into every conversation.",
    privacyTitle: "Your words stay yours.",
    privacyOnDevice: "On-device first",
    privacyOnDeviceBody:
      "Suggestions and dictation run on your iPhone whenever they can.",
    privacyCloud: "Cloud, only when you ask",
    privacyCloudBody: "Heavier AI actions call the cloud only when you tap them.",
    privacySold: "Never sold",
    privacySoldBody:
      "Your keystrokes and messages are never used for advertising.",
    downloadTitle: "Add it. Type anywhere.",
    downloadSub: "Free on iPhone. After you install the app, add the keyboard in Settings.",
    step1Title: "Install the app",
    step1Body: "Get AI Keyboard on your iPhone, then open it once.",
    step2Title: "Add the keyboard",
    step2Body:
      "Settings, General, Keyboard, Keyboards, Add New Keyboard, AI Keyboard.",
    step3Title: "Allow Full Access",
    step3Body:
      "Reply, Rewrite, and cloud dictation need it. Typing works without it.",
    footerStore: "Get the keyboard",
    footerPrivacy: "Privacy",
    footerCopy: "© 2026 AIKeyboard",
    privacyPageTitle: "Privacy",
    privacyPageLead:
      "AI Keyboard is an iOS keyboard. This page is what the product does with what you type.",
  },
  he: {
    skip: "דלג לתוכן",
    wordmark: "AIKeyboard",
    localeName: "English",
    localeSwitch: "מעבר לאנגלית",
    navCta: "להורדה",
    heroTitleA: "מקלדת ש",
    heroTitleEm: "כותבת",
    heroTitleB: "איתך.",
    heroSub: "תשובה, ניסוח והכתבה, בלי לעזוב את האפליקציה.",
    heroPrimary: "להורדה",
    heroSecondary: "לראות את זה כותב",
    sceneFrom: "מאיה",
    sceneIn: "יוצאים לאכול ביום חמישי?",
    sceneOut: "יום חמישי בשבע מצוין. נתראה!",
    suggestions: ["יום חמישי", "בטח", "נתראה"],
    space: "עברית",
    actions: ["תשובה", "תיקון", "ניסוח"],
    dictate: "הכתבה",
    storyTitle: "הודעה אחת נכתבת מקצה לקצה.",
    storySub: "גוללים. תשובה אחת נכתבת על המקשים.",
    storyUnderstand: "הבנה",
    storyUnderstandBody:
      "תשובה קוראת את השיחה ורואה שמאיה שואלת על יום חמישי.",
    storyDraft: "טיוטה",
    storyDraftBody: "תשובה מתאימה נכתבת בשדה ההודעה, בלי לעזוב את המקלדת.",
    storyRefine: "ניסוח",
    storyRefineBody: "ניסוח מעביר את הטון מקליל למקצועי בלחיצה אחת.",
    storyDictate: "הכתבה",
    storyDictateBody: "אומרים עוד משפט. הוא נוחת בהודעה, מוקלד ומפוסק.",
    storySend: "שליחה",
    storySendBody: "ההודעה המוגמרת עולה לצ'אט. לא עזבת את המקלדת.",
    storyChip: "מאיה שאלה על ארוחת ערב ביום חמישי",
    storyRough: "תודה! יום חמישי בשבע מצוין.",
    storyRefined: "תודה על ההזמנה. יום חמישי בשבע מצוין בשבילי.",
    storySpoken: "נתראה!",
    storyOut: "תודה על ההזמנה. יום חמישי בשבע מצוין בשבילי. נתראה!",
    storySent: "נשלח",
    featuresTitle: "העבודה קורית על המקשים.",
    featuresSub: "שלוש פעולות מתחת לאגודלים. השאר שומר על הכתיבה נקייה.",
    screenTitle: "תשובה",
    screenBody:
      "כשמבקשים, המקלדת קוראת את השיחה על המסך ומנסחת תשובה שמתאימה לרגע, במקום להתחיל מאפס.",
    screenChip: "קראה את ההזמנה",
    rewriteTitle: "ניסוח",
    rewriteBody: "מנסחים מחדש משפט, או מחליפים טון, בלחיצה אחת.",
    casual: "קליל",
    professional: "מקצועי",
    dictateTitle: "הכתבה",
    dictateBody: "מדברים. היא מקלידה, מפסקת, ושומעת מתי סיימת.",
    listening: "מקשיבה",
    grammarTitle: "דקדוק במקום",
    grammarBody: "איות ודקדוק מתוקנים בשפה שכותבים בה.",
    dictionaryTitle: "מילון אישי",
    dictionaryBody: "שמות ומונחים שמלמדים פעם אחת, מוצעים מכאן והלאה.",
    layoutsTitle: "פריסות מותאמות",
    layoutsBody: "סידור המקשים כמו שהידיים מצפות.",
    languagesTitle: "כותבים בשפה שחושבים בה.",
    languagesSub:
      "הצעות, תיקונים ופעולות AI עוקבים אחריך בין השפות, לשני הכיוונים.",
    languagesNote: "הפריסה והמילון האישי מגיעים איתך לכל שיחה.",
    privacyTitle: "המילים שלך נשארות שלך.",
    privacyOnDevice: "קודם על המכשיר",
    privacyOnDeviceBody: "הצעות והכתבה רצות על האייפון בכל פעם שאפשר.",
    privacyCloud: "ענן, רק כשמבקשים",
    privacyCloudBody: "פעולות AI כבדות יותר קוראות לענן רק בלחיצה.",
    privacySold: "לא נמכר",
    privacySoldBody: "ההקלדות וההודעות לא משמשות לפרסום.",
    downloadTitle: "מוסיפים. כותבים מכל מקום.",
    downloadSub: "חינם באייפון. אחרי התקנת האפליקציה, מוסיפים את המקלדת בהגדרות.",
    step1Title: "מתקינים את האפליקציה",
    step1Body: "מורידים את AI Keyboard לאייפון, ופותחים פעם אחת.",
    step2Title: "מוסיפים את המקלדת",
    step2Body: "הגדרות, כללי, מקלדת, מקלדות, הוספת מקלדת חדשה, AI Keyboard.",
    step3Title: "מאפשרים גישה מלאה",
    step3Body: "תשובה, ניסוח והכתבה בענן צריכים אותה. הקלדה רגילה עובדת בלעדיה.",
    footerStore: "להורדה",
    footerPrivacy: "פרטיות",
    footerCopy: "© 2026 AIKeyboard",
    privacyPageTitle: "פרטיות",
    privacyPageLead:
      "AI Keyboard היא מקלדת לאייפון. כאן כתוב מה המוצר עושה עם מה שכותבים.",
  },
} as const;

export type Copy = (typeof copy)[Locale];
